apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

# resources:
#   - pipeline-starter-clusterrole.yaml
#   - pipeline-starter-rolebinding.yaml
#   - pipeline-starter-sa.yaml
#   - sushiweb-build-pipline.yaml
#   - sushiweb-build-project.yaml
#   - sushiweb-build-pvc.yaml

patchesStrategicMerge:
#  - sushiweb-build-pvc.yaml

